services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"   # changed
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/eventdb

  frontend:
    build: ./frontend
    ports:
      - "3002:3000"   # changed
    depends_on:
      - backend

  db:
    image: mongo
    ports:
      - "27018:27017"   # already changed
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
